cacheFolder: /home/node/myapp-frontend/.yarn/cache

logFilters:
  - level: discard
    pattern: "* react * doesn't satisfy what @mdx-js/react requests"
  - level: discard
    pattern: "* react * doesn't satisfy what @storybook/addon-actions * request"
  - level: discard
    pattern: "* react * doesn't satisfy what @storybook/react * request"
  - level: discard
    pattern: "* react-dom * doesn't satisfy what @storybook/react * request"

packageExtensions:
  '@devtools-ds/object-inspector@1.2.0':
    peerDependencies:
      react-dom: '>= 16.8.6'
  '@devtools-ds/themes@1.2.0':
    peerDependencies:
      react-dom: '>= 16.8.6'
  '@devtools-ds/tree@1.2.0':
    peerDependencies:
      react-dom: '>= 16.8.6'
  '@storybook/addon-docs@6.5.13':
    peerDependencies:
      '@babel/core': ^7.0.0-0
      webpack: '>=2'
  '@storybook/docs-tools@6.5.13':
    peerDependencies:
      react: ^16.8.0 || ^17.0.0 || ^18.0.0
      react-dom: ^16.8.0 || ^17.0.0 || ^18.0.0
  '@storybook/instrumenter@6.5.13':
    peerDependencies:
      react: ^16.8.0 || ^17.0.0 || ^18.0.0
      react-dom: ^16.8.0 || ^17.0.0 || ^18.0.0
  '@storybook/mdx1-csf@0.0.1':
    peerDependencies:
      '@babel/core': ^7.0.0-0
  '@storybook/telemetry@6.5.13':
    peerDependencies:
      react: ^16.8.0 || ^17.0.0 || ^18.0.0
      react-dom: ^16.8.0 || ^17.0.0 || ^18.0.0
  '@storybook/testing-library@0.0.13':
    peerDependencies:
      react: ^16.8.0 || ^17.0.0 || ^18.0.0
      react-dom: ^16.8.0 || ^17.0.0 || ^18.0.0

yarnPath: .yarn/releases/yarn-3.3.0.cjs
