cacheFolder: /home/node/myapp-frontend/.yarn/cache

logFilters:
  - level: discard
    pattern: "* react * doesn't satisfy what @mdx-js/react requests"
  - level: discard
    pattern: "* react * doesn't satisfy what @storybook/addon-actions * request"
  - level: discard
    pattern: "* react * doesn't satisfy what @storybook/react * request"
  - level: discard
    pattern: "* react-dom * doesn't satisfy what @storybook/react * request"

packageExtensions:
  '@devtools-ds/object-inspector@*':
    peerDependencies:
      react-dom: '>= 16.8.6'
  '@devtools-ds/themes@*':
    peerDependencies:
      react-dom: '>= 16.8.6'
  '@devtools-ds/tree@*':
    peerDependencies:
      react-dom: '>= 16.8.6'
  '@storybook/addon-docs@*':
    peerDependencies:
      '@babel/core': ^7.0.0-0
      webpack: '>=2'
  '@storybook/docs-tools@*':
    peerDependencies:
      react: ^16.8.0 || ^17.0.0 || ^18.0.0
      react-dom: ^16.8.0 || ^17.0.0 || ^18.0.0
  '@storybook/instrumenter@*':
    peerDependencies:
      react: ^16.8.0 || ^17.0.0 || ^18.0.0
      react-dom: ^16.8.0 || ^17.0.0 || ^18.0.0
  '@storybook/mdx1-csf@*':
    peerDependencies:
      '@babel/core': ^7.0.0-0
  '@storybook/telemetry@*':
    peerDependencies:
      react: ^16.8.0 || ^17.0.0 || ^18.0.0
      react-dom: ^16.8.0 || ^17.0.0 || ^18.0.0
  '@storybook/testing-library@*':
    peerDependencies:
      react: ^16.8.0 || ^17.0.0 || ^18.0.0
      react-dom: ^16.8.0 || ^17.0.0 || ^18.0.0

yarnPath: .yarn/releases/yarn-3.4.1.cjs
