services:
  frontend:
    volumes:
      - shell-log:/home/${FRONTEND_USER_NAME}/shell_log
    command: /bin/sh -c "while sleep 1000; do :; done"
    env_file:
      - ./.devcontainer/environment/gh-token.env
volumes:
  shell-log:
