services:
  frontend:
    build:
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - bashlog:/home/${FRONTEND_USER_NAME}/bashlog
      - gh-config:/home/${FRONTEND_USER_NAME}/.config/gh
      - vscode-extensions:/home/${FRONTEND_USER_NAME}/.vscode-server/extensions
    command: /bin/sh -c "while sleep 1000; do :; done"
volumes:
  bashlog:
  gh-config:
  vscode-extensions:
